### ISSUE TITLE
Exception to stdout during install

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#136]
we get this problem to the logs during install every time, dunno if its significant but things seem to work afterwards...

```
 >>>  > Setting up depot structure for 'el7' in 'local'
  >>>     ESC[36m   ConfigureESC[0m ... ESC[1m-ESC[0ESC[1m\ESC[0ESC[1m|ESC[0ESC[1m/ESC[0m-e:1:in `eval': couldn't find HOME environment -- expanding `~' (ArgumentError)
  >>>   from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/alces-tools-0.13.0/lib/alces/tools/config.rb:41:in `block in find'
  >>>   from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/alces-tools-0.13.0/lib/alces/tools/config.rb:40:in `each'
  >>>   from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/alces-tools-0.13.0/lib/alces/tools/config.rb:40:in `find'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/config.rb:36:in `block in config'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/config.rb:35:in `tap'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/config.rb:35:in `config'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/config.rb:58:in `method_missing'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/depot.rb:60:in `each'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/dao.rb:33:in `initialize!'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/dao.rb:50:in `<module:Packager>'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/dao.rb:28:in `<module:Alces>'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/dao.rb:27:in `<top (required)>'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/package.rb:22:in `require'
  >>>   from /opt/clusterware/lib/ruby/lib/alces/packager/package.rb:22:in `<top (required)>'
  >>>   from (eval):8:in `require'
  >>>   from (eval):8:in `<main>'
  >>>   from -e:1:in `eval'
  >>>   from -e:1:in `<main>'
  >>>ESC[1m-ESC[0ESC[1m\ESC[0ESC[1m|ESC[0ESC[1m/E
```

**Comment by mjtko** [comment]
This happens if `HOME` is unset, which may be the case when clusterware installation is fully orchestrated (i.e. isn’t being driven via a login shell).

A workaround is to ensure `HOME` is set to a useful value before performing installation, but the better solution (as above commit) is to try and set `HOME` to something useful if it’s not set before trying to initialize the Gridware tree.
