### ISSUE TITLE
Error when installing gridware

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#138]
Enabled `volatile` first, then: 

```
[alces@login1(vlj) ~]$ alces gridware install apps/iozone/3.420
Preparing to install volatile/apps/iozone/3.420
error: undefined method `version' for nil:NilClass. Use --trace to view backtrace
[alces@login1(vlj) ~]$ alces gridware install apps/iozone/3.420 --trace
Preparing to install volatile/apps/iozone/3.420
/opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:166:in `compiler_tag': undefined method `version' for nil:NilClass (NoMethodError)
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/memoist-0.12.0/lib/memoist.rb:131:in `compiler_tag'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:180:in `installed?'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/memoist-0.12.0/lib/memoist.rb:175:in `installed?'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:104:in `block in find_requires'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:95:in `tap'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:95:in `find_requires'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:57:in `requirements_tree'
    from /opt/clusterware/lib/ruby/lib/alces/packager/dependency_handler.rb:60:in `resolve_requirements_tree'
    from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:130:in `install_dependencies'
    from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:114:in `install_defn'
    from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:58:in `install'
    from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:31:in `install'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:183:in `block (2 levels) in install'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:216:in `call'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:216:in `with_resource'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:198:in `with_definition'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:182:in `block in install'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:263:in `block in repository'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core/repository.rb:114:in `scope'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:263:in `repository'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:223:in `with_depot'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:181:in `install'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:50:in `block in method_missing'
    from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:245:in `block in with_clean_env'
    from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:232:in `with_original_env'
    from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:238:in `with_clean_env'
    from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:49:in `method_missing'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:179:in `call'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /opt/clusterware/libexec/actions/gridware:75:in `<main>'
```

This seems to happen with most things I try and install. Using the latest AMI in `flight-aws-marketplace` `2016.2`

**Comment by mjtko** [comment]
This is due to a problem during Clusterware installation, which should be fixed by #136.
