### ISSUE TITLE
`alces gridware info <unknown package>` gives error

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/clusterware#155]
For instance:

```
[root@login1(el7cluster) base]# alces gridware info c --trace
/opt/clusterware/lib/ruby/lib/alces/packager/display_handler.rb:75:in `info': undefined local variable or method `args' for #<Alces::Packager::DisplayHandler:0x00000000f86678> (NameError)
        from /opt/clusterware/lib/ruby/lib/alces/packager/display_handler.rb:38:in `info'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:91:in `info'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:50:in `block in method_missing'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:245:in `block in with_clean_env'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:232:in `with_original_env'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:238:in `with_clean_env'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:49:in `method_missing'
        from /opt/clusterware/dist/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:179:in `call'
        from /opt/clusterware/dist/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /opt/clusterware/dist/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /opt/clusterware/dist/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /opt/clusterware/dist/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /opt/clusterware/libexec/actions/gridware:76:in `<main>'
```

**Comment by mjtko** [comment]
Good spot! :sombrero:
